const state = { token: localStorage.getItem("gunaso_token"), user: JSON.parse(localStorage.getItem("gunaso_user") || "null") };
const app = document.querySelector("#app");
const nav = document.querySelector("#nav");
const toast = (message) => { const el = document.querySelector("#toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2600); };
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]));
async function api(path, options = {}) {
  const response = await fetch(`/api${path}`, { ...options, headers: { "Content-Type": "application/json", ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.message || "Something went wrong");
  return body;
}
function saveAuth(data) { state.token = data.token; state.user = data.user; localStorage.setItem("gunaso_token", data.token); localStorage.setItem("gunaso_user", JSON.stringify(data.user)); }
function renderNav() { nav.innerHTML = state.user ? `<a href="#dashboard">My complaints</a><a href="#new">File a complaint</a><button class="secondary" id="logout">Log out</button>` : `<a href="#login">Sign in</a><a class="button" href="#register">Create account</a>`; document.querySelector("#logout")?.addEventListener("click", () => { localStorage.clear(); state.token = null; state.user = null; location.hash = ""; render(); }); }
const form = (mode) => `<section class="panel narrow"><p class="eyebrow">${mode === "login" ? "Welcome back" : "Join your community"}</p><h2>${mode === "login" ? "Sign in to Gunaso" : "Create your account"}</h2><form id="auth-form"><label>Name${mode === "login" ? "" : " *"}<input name="name" ${mode === "login" ? "hidden" : "required"} /></label><label>Email<input type="email" name="email" required /></label><label>Password<input type="password" name="password" minlength="6" required /></label><div class="form-actions"><button>${mode === "login" ? "Sign in" : "Create account"}</button><a class="button secondary" href="#${mode === "login" ? "register" : "login"}">${mode === "login" ? "Register" : "I have an account"}</a></div><p id="form-error" class="error"></p></form></section>`;
function home() { return `<section class="hero"><p class="eyebrow">Your voice. Visible action.</p><h1>Make your community better, one report at a time.</h1><p>Gunaso connects citizens with the public offices responsible for making things right. Submit a complaint, follow its progress, and stay informed.</p><a class="button" href="#${state.user ? "new" : "register"}">${state.user ? "File a complaint" : "Get started"}</a></section>`; }
async function dashboard() { app.innerHTML = `<div class="section-head"><div><p class="eyebrow">Dashboard</p><h2>Your complaints</h2></div><a class="button" href="#new">+ File complaint</a></div><div id="complaints" class="grid"><div class="panel empty">Loading complaints...</div></div>`; try { const { complaints } = await api("/complaints"); const target = document.querySelector("#complaints"); target.innerHTML = complaints.length ? complaints.map((c) => `<article class="panel card"><div class="card-top"><span class="badge">${escapeHtml(c.status.replace("_", " "))}</span><span class="muted">${escapeHtml(c.ticketId)}</span></div><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.description.slice(0, 140))}${c.description.length > 140 ? "..." : ""}</p><a href="#complaint/${c._id}">View details →</a></article>`).join("") : `<div class="panel empty">You have not filed any complaints yet.</div>`; } catch (error) { toast(error.message); } }
function newComplaint() { app.innerHTML = `<section class="panel"><p class="eyebrow">Public service request</p><h2>File a complaint</h2><form id="complaint-form"><label>Title<input name="title" placeholder="What needs attention?" required minlength="5" maxlength="120" /></label><label>Description<textarea name="description" placeholder="Give enough detail for the right department to help." required minlength="10"></textarea></label><div class="grid"><div><label>Category<select name="category"><option value="other">Other</option><option>road</option><option>water</option><option>electricity</option><option>sanitation</option><option>health</option><option>corruption</option></select></label></div><div><label>Urgency<select name="urgency"><option>medium</option><option>low</option><option>high</option><option>critical</option></select></label></div></div><label>Location or address<input name="address" placeholder="Ward, street, or landmark" required /></label><div class="form-actions"><button>Submit complaint</button><a href="#dashboard">Cancel</a></div><p id="form-error" class="error"></p></form></section>`; document.querySelector("#complaint-form").addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); try { const result = await api("/complaints", { method: "POST", body: JSON.stringify({ ...data, location: { coordinates: [0, 0], address: data.address } }) }); toast(`Complaint ${result.complaint.ticketId} submitted`); location.hash = `#complaint/${result.complaint._id}`; } catch (error) { document.querySelector("#form-error").textContent = error.message; } }); }
async function details(id) { app.innerHTML = `<div class="panel empty">Loading complaint...</div>`; try { const { complaint, history } = await api(`/complaints/${id}`); app.innerHTML = `<a href="#dashboard">← Back to complaints</a><section class="panel" style="margin-top:18px"><div class="card-top"><div><p class="eyebrow">${escapeHtml(complaint.ticketId)}</p><h2>${escapeHtml(complaint.title)}</h2></div><span class="badge">${escapeHtml(complaint.status.replace("_", " "))}</span></div><p>${escapeHtml(complaint.description)}</p><div class="details"><div class="muted">Category<strong>${escapeHtml(complaint.category)}</strong></div><div class="muted">Urgency<strong>${escapeHtml(complaint.urgency)}</strong></div><div class="muted">Department<strong>${escapeHtml(complaint.department?.name || "Being assigned")}</strong></div><div class="muted">Location<strong>${escapeHtml(complaint.location.address || "Not provided")}</strong></div></div><h3>Activity</h3><div class="timeline">${history.map((item) => `<div class="timeline-item"><strong>${escapeHtml(item.to.replace("_", " "))}</strong><div class="muted">${new Date(item.createdAt).toLocaleString()} · ${escapeHtml(item.changedBy?.name || "System")}</div>${item.remark ? `<p>${escapeHtml(item.remark)}</p>` : ""}</div>`).join("")}</div></section>`; } catch (error) { app.innerHTML = `<div class="panel error">${escapeHtml(error.message)}</div>`; } }
async function auth(mode) { app.innerHTML = form(mode); document.querySelector("#auth-form").addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); try { saveAuth(await api(`/auth/${mode}`, { method: "POST", body: JSON.stringify(data) })); location.hash = "#dashboard"; renderNav(); } catch (error) { document.querySelector("#form-error").textContent = error.message; } }); }
function render() { renderNav(); const hash = location.hash.slice(1); if (hash === "login" || hash === "register") return auth(hash); if (!state.user) return home(); if (hash === "new") return newComplaint(); if (hash.startsWith("complaint/")) return details(hash.split("/")[1]); return dashboard(); }
window.addEventListener("hashchange", render); render();
